version: '3.8'
services:
  app:
    image: mobiauto-backend:v1
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb+srv://admin:root@mobiauto-db.hai7adv.mongodb.net/mobiauto-db?retryWrites=true&w=majority&appName=mobiauto-db

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root